/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cazzendra.pos.ui;

import cazzendra.pos.control.CashierBalanceControl;
import cazzendra.pos.core.Loading;
import cazzendra.pos.core.Validations;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Amal
 */
public class CashierBalance extends javax.swing.JDialog {

    /**
     * Creates new form EditItem
     *
     * @param parent
     * @param modal
     */
    public CashierBalance(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        panel.setBackground(Loading.getColorCode());
        comboType.requestFocus();
        Loading.customJButton(Loading.getColorR(), Loading.getColorG(), Loading.getColorB(), btAddCashBalance); 
    }

    private void clearAll() {
        txtAmount.setText(null);
        txtRemark.setText(null);
        comboType.setSelectedIndex(0);
    }

    private void addCashierBalance() {
        if (txtAmount.getText().trim().equalsIgnoreCase("") || txtAmount.getText().trim() == null) {
            JOptionPane.showMessageDialog(this, "Enter amount !", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (txtRemark.getText().trim().equalsIgnoreCase("") || txtRemark.getText().trim() == null) {
            JOptionPane.showMessageDialog(this, "Enter Remark !", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            int type = 0;
            if (comboType.getSelectedItem().toString().equalsIgnoreCase("Openning Balance")) {
                type = cazzendra.pos.model.CashierBalance.OPENING_BALANCE;
            } else if (comboType.getSelectedItem().toString().equalsIgnoreCase("Day End Balance")) {
                type = cazzendra.pos.model.CashierBalance.CLOSING_BALANCE;
            } else if (comboType.getSelectedItem().toString().equalsIgnoreCase("Expence")) {
                type = cazzendra.pos.model.CashierBalance.CASH_OUT;
            } else if (comboType.getSelectedItem().toString().equalsIgnoreCase("Cash In")) {
                type = cazzendra.pos.model.CashierBalance.CASH_IN;
            }

            boolean status = CashierBalanceControl.addCashierBalance(type, txtAmount.getText().trim(), txtRemark.getText().trim());
            if (status) {
                JOptionPane.showMessageDialog(this, "Record added successfully !", "Success", JOptionPane.INFORMATION_MESSAGE);
                clearAll();
            }

        } catch (SQLException ex) {
            Logger.getLogger(CashierBalance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btAddCashBalance = new javax.swing.JButton();
        comboType = new javax.swing.JComboBox<>();
        txtRemark = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cashier Balance");
        setMaximumSize(new java.awt.Dimension(334, 694));
        setMinimumSize(new java.awt.Dimension(334, 694));

        panel.setMaximumSize(new java.awt.Dimension(334, 694));
        panel.setMinimumSize(new java.awt.Dimension(334, 694));
        panel.setPreferredSize(new java.awt.Dimension(334, 694));

        jLabel2.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Type");

        txtAmount.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAmount.setToolTipText("Amount");
        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAmountKeyReleased(evt);
            }
        });

        btAddCashBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cazzendra/pos/newtheme/icons/save-32.png"))); // NOI18N
        btAddCashBalance.setToolTipText("Add Item");
        btAddCashBalance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAddCashBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddCashBalanceActionPerformed(evt);
            }
        });

        comboType.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Openning Balance", "Day End Balance", "Expence", "Cash In" }));
        comboType.setToolTipText("Drawer Balance");
        comboType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTypeActionPerformed(evt);
            }
        });

        txtRemark.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtRemark.setToolTipText("Amount");
        txtRemark.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRemarkKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Amount");

        jLabel4.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Remark");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btAddCashBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtRemark, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRemark, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btAddCashBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAddCashBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddCashBalanceActionPerformed
        addCashierBalance();
    }//GEN-LAST:event_btAddCashBalanceActionPerformed

    private void comboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTypeActionPerformed
        txtAmount.requestFocus();
    }//GEN-LAST:event_comboTypeActionPerformed

    private void txtAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validations.isNotEmpty(txtAmount.getText())) {
                txtRemark.requestFocus();
            }
        }
    }//GEN-LAST:event_txtAmountKeyReleased

    private void txtRemarkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRemarkKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Validations.isNotEmpty(txtRemark.getText())) {
                btAddCashBalance.requestFocus();
            }
        }
    }//GEN-LAST:event_txtRemarkKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CashierBalance dialog = new CashierBalance(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddCashBalance;
    private javax.swing.JComboBox<String> comboType;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtRemark;
    // End of variables declaration//GEN-END:variables
}
