/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cazzendra.pos.ui;

import cazzendra.pos.control.CommonController;
import cazzendra.pos.core.Loading;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author personal
 */
public class CurrentStockJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CurrentStockJFrame
     */
    public CurrentStockJFrame() {
        initComponents();
        loadDataToTable();
        panel.setBackground(Loading.getColorCode());
        Loading.customJButton(Loading.getColorR(), Loading.getColorG(), Loading.getColorB(), btnPrint);
    }

    private void loadDataToTable() {
        try {
            ResultSet rset = CommonController.getCurrentStock();
            String[] columnList = {"current_stock_item_id", "item_code", "item_barcode", "item_name", "stock"};
            CommonController.loadDataToTable(tblItemStock, rset, columnList);
        } catch (SQLException ex) {
            Logger.getLogger(CurrentStockJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchByItemName() {
        try {
            ResultSet rset = CommonController.getCurrentStockByOneAttribute(txtItemName.getText().trim());
            String[] columnList = {"current_stock_item_id", "item_code", "item_barcode", "item_name", "stock"};
            CommonController.loadDataToTable(tblItemStock, rset, columnList);
        } catch (SQLException ex) {
            Logger.getLogger(CurrentStockJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemStock = new javax.swing.JTable();
        txtItemName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Current Stock");

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblItemStock.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        tblItemStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Id ", "Item Code ", "Item Barcode", "Item Name", "Qty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItemStock.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblItemStock.getTableHeader().setFont(new Font("Ubuntu", Font.BOLD, 18));
        tblItemStock.getTableHeader().setOpaque(false);
        tblItemStock.getTableHeader().setBackground(new Color(0, 0, 102));
        tblItemStock.getTableHeader().setForeground(new Color(255, 255, 255));
        jScrollPane1.setViewportView(tblItemStock);
        if (tblItemStock.getColumnModel().getColumnCount() > 0) {
            tblItemStock.getColumnModel().getColumn(0).setMinWidth(0);
            tblItemStock.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblItemStock.getColumnModel().getColumn(0).setMaxWidth(0);
            tblItemStock.getColumnModel().getColumn(1).setMinWidth(150);
            tblItemStock.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblItemStock.getColumnModel().getColumn(1).setMaxWidth(150);
            tblItemStock.getColumnModel().getColumn(2).setMinWidth(200);
            tblItemStock.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblItemStock.getColumnModel().getColumn(2).setMaxWidth(200);
            tblItemStock.getColumnModel().getColumn(4).setMinWidth(100);
            tblItemStock.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblItemStock.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 102, 980, 560));

        txtItemName.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtItemNameKeyReleased(evt);
            }
        });
        panel.add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 330, 40));

        jLabel6.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Search By Item Name");
        panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cazzendra/pos/newtheme/icons/printer-3-32.png"))); // NOI18N
        btnPrint.setToolTipText("Save");
        btnPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        panel.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 50, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtItemNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemNameKeyReleased
        searchByItemName();
    }//GEN-LAST:event_txtItemNameKeyReleased

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            CommonController.printCommonReport("current_stock");
        } catch (SQLException | JRException ex) {
            Logger.getLogger(CurrentStockJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrentStockJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrentStockJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrentStockJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrentStockJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrentStockJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tblItemStock;
    private javax.swing.JTextField txtItemName;
    // End of variables declaration//GEN-END:variables
}
