/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cazzendra.pos.ui;

import cazzendra.pos.control.CommonController;
import cazzendra.pos.control.InvoiceControl;
import cazzendra.pos.core.Loading;
import cazzendra.pos.core.Validations;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Amal
 */
public class InvoiceHistory extends javax.swing.JDialog {

    /**
     * Creates new form SalesReport
     *
     * @param parent
     * @param modal
     */
    public InvoiceHistory(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setDefaults();
        panel.setBackground(Loading.getColorCode());
        lblPrintLanguage.setVisible(false);
        comboPrintLanguage.setVisible(false);
//        btnSearchInvoice.setVisible(false);
    }

//    private void printReport() {
//        try {
//            Map<String, Object> params = new HashMap<>();
//            params.put("fromDate", new String(CalFromDate.getDate().toLocaleString().getBytes(), "UTF-8")); // new String(CalFromDate.getDate().getBytes(), "UTF-8")
//            params.put("toDate", new String(CalToDate.getDate().toLocaleString().getBytes(), "UTF-8"));
//            Connection con = DatabaseConnection.getDatabaseConnection();
//            JasperReport jr = JasperCompileManager.compileReport("report/invoice_history.jasper");
//            JasperPrint jp = JasperFillManager.fillReport(jr, params, con);
//            JasperViewer.viewReport(jp);
//
//        } catch (JRException | SQLException | UnsupportedEncodingException ex) {
//            Logger.getLogger(SalesReport.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    private void setDefaults() {
        CalFromDate.setDate(CommonController.getCurrentJavaSqlDate());
        CalToDate.setDate(CommonController.getCurrentJavaSqlDate());

        List<JButton> btnList = new ArrayList<>();
        btnList.add(btnSearchByDateRange);
        btnList.add(btnSearchInvoice);
        btnList.add(btnPrintReport);
        Loading.customJButtonList(Loading.getColorR(), Loading.getColorG(), Loading.getColorB(), btnList);
    }

    private void loadDataByGivenDateRange() {

        try {
            ResultSet rset = InvoiceControl.getInvoicesByDateRange(
                    Validations.getSqlDateByUtilDate(CalFromDate.getDate()).toString(), Validations.getSqlDateByUtilDate(CalToDate.getDate()).toString());
            String[] columnList = {"invoice_id", "invoice_date", "invoice_time", "invoice_total"};
            CommonController.loadDataToTable(tblInvoices, rset, columnList);
        } catch (SQLException ex) {
            Logger.getLogger(InvoiceHistory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadDataByInvoiceNo() {
        try {
//            int selectedRow = tblInvoices.getSelectedRow();
            ResultSet rset = InvoiceControl.getInvoiceResultSetByInvoiceNo(txtInvoiceNo.getText().trim());
            String[] columnList = {"invoice_id", "invoice_date", "invoice_time", "invoice_total"};
            CommonController.loadDataToTable(tblInvoices, rset, columnList);
        } catch (SQLException ex) {
            Logger.getLogger(InvoiceHistory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void rePrint() {
        int selectedRow = tblInvoices.getSelectedRow();
        if (selectedRow != -1) {
            try {
                CommonController.printInvoice(tblInvoices.getValueAt(selectedRow, 0).toString(), comboPrintLanguage.getSelectedItem().toString());
                this.dispose();
            } catch (SQLException | JRException ex) {
                Logger.getLogger(InvoiceHistory.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        CalFromDate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CalToDate = new com.toedter.calendar.JDateChooser();
        btnSearchByDateRange = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInvoices = new javax.swing.JTable();
        txtInvoiceNo = new javax.swing.JTextField();
        btnSearchInvoice = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnPrintReport = new javax.swing.JButton();
        lblPrintLanguage = new javax.swing.JLabel();
        comboPrintLanguage = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Invoice History And Reprint");
        setMaximumSize(new java.awt.Dimension(1024, 694));
        setMinimumSize(new java.awt.Dimension(1024, 694));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 694));

        panel.setMaximumSize(new java.awt.Dimension(1024, 694));
        panel.setMinimumSize(new java.awt.Dimension(1024, 694));
        panel.setPreferredSize(new java.awt.Dimension(1024, 694));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CalFromDate.setToolTipText("Date");
        CalFromDate.setDateFormatString("yyyy-MM-dd");
        CalFromDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panel.add(CalFromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 49, 237, 38));

        jLabel6.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("From Date");
        panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 22, 215, -1));

        jLabel7.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("To Date");
        panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 22, 215, -1));

        CalToDate.setToolTipText("Date");
        CalToDate.setDateFormatString("yyyy-MM-dd");
        CalToDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CalToDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CalToDateKeyReleased(evt);
            }
        });
        panel.add(CalToDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 49, 234, 38));

        btnSearchByDateRange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cazzendra/pos/newtheme/icons/search-9-32.png"))); // NOI18N
        btnSearchByDateRange.setToolTipText("Search");
        btnSearchByDateRange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchByDateRange.setMaximumSize(new java.awt.Dimension(40, 40));
        btnSearchByDateRange.setMinimumSize(new java.awt.Dimension(40, 40));
        btnSearchByDateRange.setPreferredSize(new java.awt.Dimension(40, 40));
        btnSearchByDateRange.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnSearchByDateRangeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSearchByDateRangeFocusLost(evt);
            }
        });
        btnSearchByDateRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByDateRangeActionPerformed(evt);
            }
        });
        panel.add(btnSearchByDateRange, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 47, -1, -1));

        tblInvoices.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        tblInvoices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice No", "Date", "Time", "Invoice Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInvoices.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblInvoices.getTableHeader().setFont(new Font("Ubuntu", Font.BOLD, 18));
        tblInvoices.getTableHeader().setOpaque(false);
        tblInvoices.getTableHeader().setBackground(new Color(0, 0, 102));
        tblInvoices.getTableHeader().setForeground(new Color(255, 255, 255));
        tblInvoices.setRowHeight(22);
        jScrollPane1.setViewportView(tblInvoices);

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 114, 989, 560));

        txtInvoiceNo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtInvoiceNo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtInvoiceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInvoiceNoActionPerformed(evt);
            }
        });
        txtInvoiceNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInvoiceNoKeyReleased(evt);
            }
        });
        panel.add(txtInvoiceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 208, 40));

        btnSearchInvoice.setBackground(new java.awt.Color(255, 255, 255));
        btnSearchInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cazzendra/pos/newtheme/icons/search-9-32.png"))); // NOI18N
        btnSearchInvoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchInvoice.setMaximumSize(new java.awt.Dimension(40, 40));
        btnSearchInvoice.setMinimumSize(new java.awt.Dimension(40, 40));
        btnSearchInvoice.setPreferredSize(new java.awt.Dimension(40, 40));
        btnSearchInvoice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnSearchInvoiceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSearchInvoiceFocusLost(evt);
            }
        });
        btnSearchInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchInvoiceActionPerformed(evt);
            }
        });
        btnSearchInvoice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnSearchInvoiceKeyReleased(evt);
            }
        });
        panel.add(btnSearchInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Invoice No");
        panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 215, -1));

        btnPrintReport.setBackground(new java.awt.Color(255, 255, 255));
        btnPrintReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cazzendra/pos/newtheme/icons/printer-3-32.png"))); // NOI18N
        btnPrintReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrintReport.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnPrintReportFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnPrintReportFocusLost(evt);
            }
        });
        btnPrintReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReportActionPerformed(evt);
            }
        });
        btnPrintReport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnPrintReportKeyReleased(evt);
            }
        });
        panel.add(btnPrintReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, 40, 40));

        lblPrintLanguage.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        lblPrintLanguage.setForeground(new java.awt.Color(0, 0, 102));
        lblPrintLanguage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cloudrevel/language/src/mainmenu/print-language-sinhala.png"))); // NOI18N
        panel.add(lblPrintLanguage, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 192, -1));

        comboPrintLanguage.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        comboPrintLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Sinhala" }));
        comboPrintLanguage.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboPrintLanguagePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        comboPrintLanguage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                comboPrintLanguageKeyReleased(evt);
            }
        });
        panel.add(comboPrintLanguage, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 192, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchByDateRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByDateRangeActionPerformed
//        printReport();
        loadDataByGivenDateRange();
    }//GEN-LAST:event_btnSearchByDateRangeActionPerformed

    private void CalToDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CalToDateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CalToDateKeyReleased

    private void txtInvoiceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInvoiceNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInvoiceNoActionPerformed

    private void txtInvoiceNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInvoiceNoKeyReleased
        loadDataByInvoiceNo();
    }//GEN-LAST:event_txtInvoiceNoKeyReleased

    private void btnSearchInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchInvoiceActionPerformed
//        itemSearchAndSetDetails();
        loadDataByInvoiceNo();
    }//GEN-LAST:event_btnSearchInvoiceActionPerformed

    private void btnSearchInvoiceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSearchInvoiceKeyReleased

    }//GEN-LAST:event_btnSearchInvoiceKeyReleased

    private void btnPrintReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReportActionPerformed
        rePrint();
    }//GEN-LAST:event_btnPrintReportActionPerformed

    private void btnPrintReportKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPrintReportKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintReportKeyReleased

    private void comboPrintLanguagePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboPrintLanguagePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPrintLanguagePopupMenuWillBecomeInvisible

    private void comboPrintLanguageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboPrintLanguageKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPrintLanguageKeyReleased

    private void btnSearchByDateRangeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSearchByDateRangeFocusGained
        Loading.customJButton(255, 0, 0, btnSearchByDateRange);

    }//GEN-LAST:event_btnSearchByDateRangeFocusGained

    private void btnSearchInvoiceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSearchInvoiceFocusGained
        Loading.customJButton(255, 0, 0, btnSearchInvoice);
    }//GEN-LAST:event_btnSearchInvoiceFocusGained

    private void btnPrintReportFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnPrintReportFocusGained
        Loading.customJButton(255, 0, 0, btnPrintReport);
    }//GEN-LAST:event_btnPrintReportFocusGained

    private void btnSearchByDateRangeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSearchByDateRangeFocusLost
        Loading.customJButton(Loading.getColorR(), Loading.getColorG(), Loading.getColorB(), btnSearchByDateRange);
    }//GEN-LAST:event_btnSearchByDateRangeFocusLost

    private void btnSearchInvoiceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSearchInvoiceFocusLost
        Loading.customJButton(Loading.getColorR(), Loading.getColorG(), Loading.getColorB(), btnSearchInvoice);
    }//GEN-LAST:event_btnSearchInvoiceFocusLost

    private void btnPrintReportFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnPrintReportFocusLost
        Loading.customJButton(Loading.getColorR(), Loading.getColorG(), Loading.getColorB(), btnPrintReport);
    }//GEN-LAST:event_btnPrintReportFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InvoiceHistory dialog = new InvoiceHistory(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser CalFromDate;
    private com.toedter.calendar.JDateChooser CalToDate;
    private javax.swing.JButton btnPrintReport;
    private javax.swing.JButton btnSearchByDateRange;
    private javax.swing.JButton btnSearchInvoice;
    private javax.swing.JComboBox<String> comboPrintLanguage;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPrintLanguage;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tblInvoices;
    private javax.swing.JTextField txtInvoiceNo;
    // End of variables declaration//GEN-END:variables
}
