/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cazzendra.pos.ui;

import cazzendra.pos.control.CommonController;
import cazzendra.pos.core.Loading;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Amal
 */
public class ReorderItems extends javax.swing.JDialog {

    /**
     * Creates new form SalesReport
     *
     * @param parent
     * @param modal
     */
    public ReorderItems(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadDataToTable();
        panel.setBackground(Loading.getColorCode());
    }

    private void loadDataToTable() {
        try {
            ResultSet rset = CommonController.getCurrentStockLowerThanReorderlevel();
            String[] columnList = {"current_stock_item_id", "item_code", "item_barcode", "item_name", "stock_qty"};

            CommonController.loadDataToTable(tblItemStock, rset, columnList);
        } catch (SQLException ex) {
            Logger.getLogger(ReorderItems.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemStock = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reorder Items");
        setResizable(false);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblItemStock.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        tblItemStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Id ", "Item Code ", "Item Barcode", "Item Name", "Qty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItemStock.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblItemStock.getTableHeader().setFont(new Font("Ubuntu", Font.BOLD, 18));
        tblItemStock.getTableHeader().setOpaque(false);
        tblItemStock.getTableHeader().setBackground(new Color(0, 0, 102));
        tblItemStock.getTableHeader().setForeground(new Color(255, 255, 255));
        jScrollPane1.setViewportView(tblItemStock);
        if (tblItemStock.getColumnModel().getColumnCount() > 0) {
            tblItemStock.getColumnModel().getColumn(0).setMinWidth(0);
            tblItemStock.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblItemStock.getColumnModel().getColumn(0).setMaxWidth(0);
            tblItemStock.getColumnModel().getColumn(1).setMinWidth(150);
            tblItemStock.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblItemStock.getColumnModel().getColumn(1).setMaxWidth(150);
            tblItemStock.getColumnModel().getColumn(2).setMinWidth(150);
            tblItemStock.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblItemStock.getColumnModel().getColumn(2).setMaxWidth(150);
            tblItemStock.getColumnModel().getColumn(3).setResizable(false);
            tblItemStock.getColumnModel().getColumn(4).setMinWidth(100);
            tblItemStock.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblItemStock.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 62, 734, 390));

        jLabel8.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Reorder Items");
        panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cazzendra/pos/newtheme/icons/printer-3-32.png"))); // NOI18N
        btnSave.setToolTipText("Save");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        panel.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
//            CommonController.printReOrderItems();      
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReorderItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReorderItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReorderItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReorderItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReorderItems dialog = new ReorderItems(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tblItemStock;
    // End of variables declaration//GEN-END:variables
}
