/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cazzendra.pos.ui;

/**
 *
 * @author Amal
 */
public class Reports extends javax.swing.JFrame {

    /**
     * Creates new form ActivationUI
     */
    public Reports() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblAllItemReport = new javax.swing.JLabel();
        lblAllItemReport1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reports");
        setMaximumSize(new java.awt.Dimension(300, 412));
        setMinimumSize(new java.awt.Dimension(300, 412));
        setResizable(false);

        panel.setBackground(new java.awt.Color(0, 102, 102));
        panel.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        panel.setMaximumSize(new java.awt.Dimension(325, 412));
        panel.setMinimumSize(new java.awt.Dimension(325, 412));
        panel.setPreferredSize(new java.awt.Dimension(325, 412));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 51));
        panel.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        lblAllItemReport.setBackground(new java.awt.Color(0, 153, 255));
        lblAllItemReport.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblAllItemReport.setForeground(new java.awt.Color(255, 255, 255));
        lblAllItemReport.setText("ITEMS DETAILS ");
        lblAllItemReport.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAllItemReport.setOpaque(true);
        lblAllItemReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAllItemReportMouseClicked(evt);
            }
        });
        panel.add(lblAllItemReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 260, 30));

        lblAllItemReport1.setBackground(new java.awt.Color(0, 153, 255));
        lblAllItemReport1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblAllItemReport1.setForeground(new java.awt.Color(255, 255, 255));
        lblAllItemReport1.setText("INVOICE HISTORY & REPRINT");
        lblAllItemReport1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAllItemReport1.setOpaque(true);
        lblAllItemReport1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAllItemReport1MouseClicked(evt);
            }
        });
        panel.add(lblAllItemReport1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 260, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblAllItemReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAllItemReportMouseClicked

    }//GEN-LAST:event_lblAllItemReportMouseClicked

    private void lblAllItemReport1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAllItemReport1MouseClicked
        new InvoiceHistory(this, true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblAllItemReport1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAllItemReport;
    private javax.swing.JLabel lblAllItemReport1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
